server {
    listen 80;
    server_name 8.140.215.49 pinhaoke.love www.pinhaoke.love;

    gzip on;
    gzip_types text/html application/json text/css application/javascript;
    gzip_min_length 1000;

    location /Images/ {
        alias /opt/pinhaoke/Images/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering on;
    }
}
